on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - '!master'

name: api-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Installation
      run: |
        npm i

    - name: Setup
      run: |
        npm i