on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

name: api-test

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Setup Database
      run: |
        sudo apt-get install -y mysql-client
        cd api/tests/openapi
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword < directus.sql
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SELECT user,host FROM mysql.user"
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'"
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Installation
      run: |
        npm install
        npm run clean
        npm run bootstrap
        cd api
        npm install
        mv ./tests/openapi/test.env ./.env
        npm run build
        
    
    - name: Test
      run: |
        cd api
        npm run start
        npm run tests:openapi
