on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

name: api-test

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: directus
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Verify SQL Connection
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Installation
      run: |
        npm i
        mv /tests/openapi/.env /
    
    - name: Build
      run: |
        npm run build
    
    - name: Test
      run: |
        npm run start
        npm run tests:openapi
